#!/usr/bin/env php
<?php
/**
 * 避免服务运行报错，禁用exit、die，以下结构需做调整
 */

if( !isset($argv[1]) ){

    var_dump("请输入执行控制器");

}elseif( !file_exists(__DIR__.'/console/'.ucfirst($argv[1]).'Controller.php') ){

    var_dump("没有找到执行控制器");

}else{

    include __DIR__.'/console/'.ucfirst($argv[1]).'Controller.php';
    $class = new ReflectionClass(ucfirst($argv[1]).'Controller');
    $action = isset($argv[2])?$argv[2]:'index';
    if( !$class->hasMethod( 'action'.$action ) ){
        var_dump("没有找到执行方法");
    }else{
        $instance  = $class->newInstanceArgs();
        $method = $class->getmethod('action'.$action ); // 获取类中方法
        $result = $method->invoke($instance);    // 执行方法
    }
}


